apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-to-delete
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-delete # You can use the default one or other Storage Class with Delete as Reclaim Policy
  volumeName: pv-to-delete
