apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-delete
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
